export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ENABLE_NOTIFICATION = 'ENABLE_NOTIFICATION';
export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const GET_DEVICE_TYPES = 'GET_DEVICE_TYPES';
export const GET_DEVICE_TYPES_IN_PROGRESS = 'GET_DEVICE_TYPES_IN_PROGRESS';
export const GET_DEVICE_TYPES_SUCCESSFUL = 'GET_DEVICE_TYPES_SUCCESSFUL';
export const GET_DEVICE_TYPES_FAILED = 'GET_DEVICE_TYPES_FAILED';

export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_IN_PROGRESS = 'GET_DEVICES_IN_PROGRESS';
export const GET_DEVICES_SUCCESSFUL = 'GET_DEVICES_SUCCESSFUL';
export const GET_DEVICES_FAILED = 'GET_DEVICES_FAILED';

export const ADD_NEW_DEVICE = 'ADD_NEW_DEVICE';
export const ADD_NEW_DEVICE_IN_PROGRESS = 'ADD_NEW_DEVICE_IN_PROGRESS';
export const ADD_NEW_DEVICE_SUCCESSFUL = 'ADD_NEW_DEVICE_SUCCESSFUL';
export const ADD_NEW_DEVICE_FAILED = 'ADD_NEW_DEVICE_FAILED';
