export const GET_BOOKS_LIST = 'GET_BOOKS_LIST';
export const GET_BOOKS_LIST_IN_PROGRESS = 'GET_BOOKS_LIST_IN_PROGRESS';
export const GET_BOOKS_LIST_SUCCESSFUL = 'GET_BOOKS_LIST_SUCCESSFUL';
export const GET_BOOKS_LIST_FAILED = 'GET_BOOKS_LIST_FAILED';
